language: java
jdk:
 - openjdk11
deploy:
 provider: heroku
 api_key:
  secure: epVhV45mBswHI9XSuXpiXkha8JEIf3WI+iYlPgDFNV2xEIiD9uO9jhYFqlcZdFJgXoAH2iDRMPTRa8I6sPPS6/t4U2UuBQQuS8t0OZGT4E6KenWSWmAigd9+U+Fh5dnBANsvoNRAkuknnTErhJk26pzbncV5zOLHYYQWYBtATeppwTa6TbYa62jswmUoJvSExPha+ptPmuaciKHz+raOFKfS7HhrOL8+uBp5/wcxunZzLV789bhTSD11XhEm8I4zwWhm6j+HmM179d887fD9DuLUglYhJ+P0BIHMD2MU0PLHN3oF3EKrcbOAAYUcIdgPryJzdsradYaXsAU6WR07h/PVcbxzeSQucNOjDITGc+ydcORLgKbPq8fFiNwHOoaqXa/CbxiEaW3Z7z7rBfLjsFQDZapnf0hiEoFFnHKT4La/kBYdxXuW8Xn6vAz6LEva4G4I90rlO0xEhuuBFbqWMGSjKIcUSQ0hmFLMxSwvXaT/dWSUkpZyYdl1X7tLlbt57STOZs8JelIEFIqOe/YxXV+aQRpHDjG65WDr5pAJ4+jEp9vPVMfBYGQvGVXFdAaR2m9Z08OcZl8/h2ew4F1pEqZ+02O+8cWqIDVjzYlIBzcp1HmOnOiy9GKAMDYkXicP2TJpZgKp7xXrH9cF+Qce1RU9/SW/2RW603rmau8Bsp0=
 app: veterinarity
